pub struct Quote {
    pub text: &'static str,
    pub author: &'static str,
}

pub fn get_quotes() -> Vec<Quote> {
    vec![
        Quote { text: "Be present in all things and thankful for all things.", author: "Maya Angelou" },
        Quote { text: "Life is a dance. Mindfulness is witnessing that dance.", author: "Amit Ray" },
        Quote { text: "The present moment is filled with joy and happiness. If you are attentive, you will see it.", author: "Thich Nhat Hanh" },
        Quote { text: "Wherever you are, be there totally.", author: "Eckhart Tolle" },
        Quote { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
        Quote { text: "Realize deeply that the present moment is all you have.", author: "Eckhart Tolle" },
        Quote { text: "Mindfulness is the key to the present moment.", author: "Eckhart Tolle" },
        Quote { text: "Each morning we are born again. What we do today is what matters most.", author: "Buddha" },
        Quote { text: "Smile, breathe and go slowly.", author: "Thich Nhat Hanh" },
        Quote { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
        Quote { text: "The only way to make sense out of change is to plunge into it, move with it, and join the dance.", author: "Alan Watts" },
        Quote { text: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", author: "Thich Nhat Hanh" },
        Quote { text: "Walk as if you are kissing the Earth with your feet.", author: "Thich Nhat Hanh" },
        Quote { text: "When you realize nothing is lacking, the whole world belongs to you.", author: "Lao Tzu" },
        Quote { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
        Quote { text: "If you want to conquer the anxiety of life, live in the moment, live in the breath.", author: "Amit Ray" },
        Quote { text: "The best way to capture moments is to pay attention. This is how we cultivate mindfulness.", author: "Jon Kabat-Zinn" },
        Quote { text: "Look past your thoughts, so you may drink the pure nectar of This Moment.", author: "Rumi" },
        Quote { text: "Be happy in the moment, that's enough. Each moment is all we need, not more.", author: "Mother Teresa" },
        Quote { text: "The little things? The little moments? They aren't little.", author: "Jon Kabat-Zinn" },
        Quote { text: "Mindfulness isn't difficult, we just need to remember to do it.", author: "Sharon Salzberg" },
        Quote { text: "Nothing ever happened in the past that prevented you from being present now.", author: "Eckhart Tolle" },
        Quote { text: "Your presence is the most precious gift you can give to another human being.", author: "Thich Nhat Hanh" },
        Quote { text: "In today's rush, we all think too much — seek too much — want too much — and forget about the joy of just being.", author: "Eckhart Tolle" },
        Quote { text: "Everything is created twice, first in the mind and then in reality.", author: "Robin Sharma" },
        Quote { text: "What you think, you become. What you feel, you attract. What you imagine, you create.", author: "Buddha" },
        Quote { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
        Quote { text: "The mind is everything. What you think you become.", author: "Buddha" },
        Quote { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha" },
        Quote { text: "You, yourself, as much as anybody in the entire universe, deserve your love and affection.", author: "Buddha" },
        Quote { text: "It is better to conquer yourself than to win a thousand battles.", author: "Buddha" },
        Quote { text: "The only real failure in life is not to be true to the best one knows.", author: "Buddha" },
        Quote { text: "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", author: "Buddha" },
        Quote { text: "Just as a candle cannot burn without fire, men cannot live without a spiritual life.", author: "Buddha" },
        Quote { text: "Do not overrate what you have received, nor envy others. He who envies others does not obtain peace of mind.", author: "Buddha" },
        Quote { text: "To keep the body in good health is a duty... otherwise we shall not be able to keep our mind strong and clear.", author: "Buddha" },
        Quote { text: "We are shaped by our thoughts; we become what we think. When the mind is pure, joy follows like a shadow that never leaves.", author: "Buddha" },
        Quote { text: "There is no path to happiness: happiness is the path.", author: "Buddha" },
        Quote { text: "You only lose what you cling to.", author: "Buddha" },
        Quote { text: "The trouble is, you think you have time.", author: "Buddha" },
        Quote { text: "If you light a lamp for someone else it will also brighten your path.", author: "Buddha" },
        Quote { text: "Silence is an empty space, space is the home of the awakened mind.", author: "Buddha" },
        Quote { text: "Better than a thousand hollow words, is one word that brings peace.", author: "Buddha" },
        Quote { text: "Every morning we are born again. What we do today is what matters most.", author: "Buddha" },
        Quote { text: "Purity or impurity depends on oneself, no one can purify another.", author: "Buddha" },
        Quote { text: "However many holy words you read, however many you speak, what good will they do you if you do not act on upon them?", author: "Buddha" },
        Quote { text: "The secret of health for both mind and body is not to mourn for the past, worry about the future, or anticipate troubles, but to live in the present moment wisely and earnestly.", author: "Buddha" },
        Quote { text: "To understand everything is to forgive everything.", author: "Buddha" },
        Quote { text: "Happiness never decreases by being shared.", author: "Buddha" },
        Quote { text: "Radiate boundless love towards the entire world.", author: "Buddha" },
        Quote { text: "Muddy water is best cleared by leaving it alone.", author: "Alan Watts" },
        Quote { text: "This is the real secret of life -- to be completely engaged with what you are doing in the here and now. And instead of calling it work, realize it is play.", author: "Alan Watts" },
        Quote { text: "The art of living... is neither careless drifting on the one hand nor fearful clinging to the past on the other. It consists in being sensitive to each moment, in regarding it as utterly new and unique, in having the mind open and wholly receptive.", author: "Alan Watts" },
        Quote { text: "To have faith is to trust yourself to the water. When you swim you don't grab hold of the water, because if you do you will sink and drown. Instead you relax, and float.", author: "Alan Watts" },
        Quote { text: "Trying to define yourself is like trying to bite your own teeth.", author: "Alan Watts" },
        Quote { text: "Man suffers only because he takes seriously what the gods made for fun.", author: "Alan Watts" },
        Quote { text: "No work or love will flourish out of guilt, fear, or hollowness of heart, just as no valid plans for the future can be made by those who have no capacity for living now.", author: "Alan Watts" },
        Quote { text: "When we dance, the journey itself is the point, as when we play music the playing itself is the point.", author: "Alan Watts" },
        Quote { text: "You are an aperture through which the universe is looking at and exploring itself.", author: "Alan Watts" },
        Quote { text: "Things are as they are. Looking out into it the universe at night, we make no comparisons between right and wrong stars, nor between well and badly arranged constellations.", author: "Alan Watts" },
        Quote { text: "Without birth and death, and without the perpetual transmutation of all the forms of life, the world would be static, rhythm-less, undancing, mummified.", author: "Alan Watts" },
        Quote { text: "The more a thing tends to be permanent, the more it tends to be lifeless.", author: "Alan Watts" },
        Quote { text: "We cannot be more sensitive to pleasure without being more sensitive to pain.", author: "Alan Watts" },
        Quote { text: "Every individual is a unique manifestation of the Whole, as every branch is a particular outreaching of the tree.", author: "Alan Watts" },
        Quote { text: "A scholar tries to learn something everyday; a student of Buddhism tries to unlearn something everyday.", author: "Alan Watts" },
        Quote { text: "Problems that remain persistently insoluble should always be suspected as questions asked in the wrong way.", author: "Alan Watts" },
        Quote { text: "If you cannot trust yourself, you cannot even trust your mistrust of yourself - so that without this underlying trust in the whole system of nature you are simply paralyzed.", author: "Alan Watts" },
        Quote { text: "The menu is not the meal.", author: "Alan Watts" },
        Quote { text: "Technology is destructive only in the hands of people who do not realize that they are one and the same process as the universe.", author: "Alan Watts" },
        
        // Elon Musk
        Quote { text: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk" },
        Quote { text: "Persistence is very important. You should not give up unless you are forced to give up.", author: "Elon Musk" },
        Quote { text: "I think it is possible for ordinary people to choose to be extraordinary.", author: "Elon Musk" },
        Quote { text: "If you get up in the morning and think the future is going to be better, it is a bright day. Otherwise, it's not.", author: "Elon Musk" },

        // Albert Einstein
        Quote { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
        Quote { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
        Quote { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
        Quote { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },

        // Steve Jobs
        Quote { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
        Quote { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
        Quote { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },

        // Naval Ravikant
        Quote { text: "Impatience with actions, patience with results.", author: "Naval Ravikant" },
        Quote { text: "Easy choices, hard life. Hard choices, easy life.", author: "Naval Ravikant" },
        Quote { text: "Play long-term games with long-term people.", author: "Naval Ravikant" },

        // Others
        Quote { text: "Live in the future, then build what's missing.", author: "Paul Graham" },
        Quote { text: "The days are long but the decades are short.", author: "Sam Altman" },
        Quote { text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "James Clear" },

        // Proverbs
        Quote { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
        Quote { text: "A journey of a thousand miles begins with a single step.", author: "Chinese Proverb" },
        Quote { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
        Quote { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
        Quote { text: "This too shall pass.", author: "Persian Adage" },
        Quote { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" }, // Fitting here
        Quote { text: "When the winds of change blow, some people build walls and others build windmills.", author: "Chinese Proverb" },
        Quote { text: "A smooth sea never made a skilled sailor.", author: "English Proverb" },
        Quote { text: "Vision without action is a daydream. Action without vision is a nightmare.", author: "Japanese Proverb" },
        Quote { text: "Measure twice, cut once.", author: "Proverb" },

        // Jordan Peterson
        Quote { text: "Compare yourself to who you were yesterday, not to who someone else is today.", author: "Jordan Peterson" },
        Quote { text: "Set your house in perfect order before you criticize the world.", author: "Jordan Peterson" },
        Quote { text: "Pursue what is meaningful (not what is expedient).", author: "Jordan Peterson" },
        Quote { text: "Tell the truth – or, at least, don't lie.", author: "Jordan Peterson" },
        Quote { text: "You're going to pay a price for every bloody thing you do and everything you don't do. You don't get to choose to not pay a price. You get to choose which poison you're going to take.", author: "Jordan Peterson" },

        // Andrew Tate
        Quote { text: "The temporary satisfaction of quitting is outweighed by the eternal suffering of being a nobody.", author: "Andrew Tate" },
        Quote { text: "You are exactly where you deserve to be. Change who you are and you will change how you live.", author: "Andrew Tate" },
        Quote { text: "Do the impossible and you'll never doubt yourself ever again.", author: "Andrew Tate" },
        Quote { text: "Arrogance breeds complacency and complacency breeds failure.", author: "Andrew Tate" },
        Quote { text: "Cost is the enemy of the poor man, so the poor try to save money. Time is the enemy of the rich man, so the rich try to save time.", author: "Andrew Tate" },

        // Biblical & Spiritual
        Quote { text: "Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.", author: "Jesus Christ" },
        Quote { text: "Can any one of you by worrying add a single hour to your life?", author: "Jesus Christ" },
        Quote { text: "To everything there is a season, and a time to every purpose under the heaven.", author: "King Solomon" },
        Quote { text: "Whatever your hand finds to do, do it with all your might.", author: "King Solomon" },
        Quote { text: "This is the day the Lord has made; let us rejoice and be glad in it.", author: "King David" },
        Quote { text: "Be still, and know that I am God.", author: "Psalm 46:10" },

        // Eckhart Tolle & Presence
        Quote { text: "Realize deeply that the present moment is all you have. Make the NOW the primary focus of your life.", author: "Eckhart Tolle" },
        Quote { text: "Unease, anxiety, tension, stress, worry - all forms of fear - are caused by too much future, and not enough presence.", author: "Eckhart Tolle" },
        Quote { text: "The past has no power over the present moment.", author: "Eckhart Tolle" },

        // Eastern Philosophy
        Quote { text: "If you are depressed you are living in the past. If you are anxious you are living in the future. If you are at peace you are living in the present.", author: "Lao Tzu" },
        Quote { text: "When walking, walk. When eating, eat.", author: "Zen Proverb" },
        Quote { text: "Do not let the behavior of others destroy your inner peace.", author: "Dalai Lama" },

        // Classical Philosophy
        Quote { text: "The unexamined life is not worth living.", author: "Socrates" },
        Quote { text: "To know thyself is the beginning of wisdom.", author: "Socrates" },
        Quote { text: "I cannot teach anybody anything. I can only make them think.", author: "Socrates" },
        Quote { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
        Quote { text: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", author: "Plato" },
        Quote { text: "The first and greatest victory is to conquer yourself.", author: "Plato" },
        Quote { text: "Wise men speak because they have something to say; fools because they have to say something.", author: "Plato" },
        Quote { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
        Quote { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
        Quote { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
        Quote { text: "You have power over your mind - not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
        Quote { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
        Quote { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
        Quote { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius" },
        Quote { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
        Quote { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
        Quote { text: "It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.", author: "Seneca" },
        Quote { text: "He who is brave is free.", author: "Seneca" },
        Quote { text: "No man is free who is not master of himself.", author: "Epictetus" },
        Quote { text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus" },
        Quote { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
    ]
}
